const PostsActionTypes = {
  ADD_POST: "ADD_POST",
  EDIT_POST: "EDIT_POST",
  DELETE_POST_START: "DELETE_POST_START",
  DELETE_POST_FINISH: "DELETE_POST_FINISH",
  DELETE_POST_CANCEL: "DELETE_POST_CANCEL",
  SET_POSTS: "SET_POSTS",
  SET_USERINFO: "SET_USERINFO",
  SET_POSTS_USER: "SET_POSTS_USER",
  SET_SELECTED_POST: "SET_SELECTED_POST",
  RESET_SELECTED_POST: "RESET_SELECTED_POST",
  RESET_POSTS: "RESET_POSTS",
};

export default PostsActionTypes;
