const CommentsActionTypes = {
  SET_COMMENTS: "SET_COMMENTS",
  ADD_COMMENT: "ADD_COMMENT",
  DELETE_COMMENT_START: "DELETE_COMMENT_START",
  DELETE_COMMENT_FINISH: "DELETE_COMMENT_FINISH",
  DELETE_COMMENT_CANCEL: "DELETE_COMMENT_CANCEL",
  RESET_COMMENTS: "RESET_COMMENTS",
};

export default CommentsActionTypes;
