const ContentsActionTypes = {
  ADD_CONTENT: "ADD_CONTENT",
  EDIT_CONTENT: "EDIT_CONTENT",
  DELETE_CONTENT_START: "DELETE_CONTENT_START",
  DELETE_CONTENT_FINISH: "DELETE_CONTENT_FINISH",
  DELETE_CONTENT_CANCEL: "DELETE_CONTENT_CANCEL",
  SET_CONTENTS: "SET_CONTENTS",
  SET_VIDEO_CONTENT: "SET_VIDEO_CONTENT",
  SET_SELECTED_CONTENT: "SET_SELECTED_CONTENT",
  RESET_SELECTED_CONTENT: "RESET_SELECTED_CONTENT",
  RESET_CONTENTS: "RESET_CONTENTS",
  RESET_FILTERED_CONTENTS: "RESET_FILTERED_CONTENTS",
};

export default ContentsActionTypes;
