const coursesActionTypes = {
  ADD_COURSE: "ADD_COURSE",
  EDIT_COURSE: "EDIT_COURSE",
  DELETE_COURSE_START: "DELETE_COURSE_START",
  DELETE_COURSE_FINISH: "DELETE_COURSE_FINISH",
  DELETE_COURSE_CANCEL: "DELETE_COURSE_CANCEL",
  SET_COURSES: "SET_COURSES",
  SET_SELECTED_COURSE: "SET_SELECTED_COURSE",
  RESET_SELECTED_COURSE: "RESET_SELECTED_COURSE",
  RESET_SELECTED_COURSE_CONTENTS: "RESET_SELECTED_COURSE_CONTENTS",
  RESET_COURSES: "RESET_COURSES",
  SET_SELECTED_COURSE_CONTENTS: "SET_SELECTED_COURSE_CONTENTS",
  SET_FILTERED_COURSES: "SET_FILTERED_COURSES",
  RESET_FILTERED_COURSES: "RESET_FILTERED_COURSES",
};

export default coursesActionTypes;
